version: '3'

services:
  database:
    image: postgres:14.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=somestrongpassword
      - POSTGRES_DB=friendly-system
    networks:
      - fs_network
    volumes:
      - fs_database:/var/lib/postgresql/data
    
  app:
    build:
      context: ./frontend/
      #dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - fs_network
  
  app-api:
    build:
      context: ./backend
    ports:
      - 3333:3333
    networks:
      - fs_network

networks:
  fs_network:

volumes:
  fs_database: