version: '3'
# Set environment variables in .env or keep default fallback values

services:
  database:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-somestrongpassword}
      - POSTGRES_DB=${DB_NAME:-friendly-system}
    networks:
      - fs_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${DB_NAME:-friendly-system}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - fs_database:/var/lib/postgresql/data
      #- fs_database-development:/var/lib/postgresql/data
    
  app-web:
    build:
      context: ./frontend/
      args:
        API_URL: ${API_URL:-localhost}:${API_PORT:-3333}
      #dockerfile: Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    networks:
      - fs_network
  
  app-api:
    build:
      context: ./backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - WEB_URL=${WEB_URL:-localhost}
      - PYTHON_URL=${SNMPAGENT_URL:-http://app-snmpagent:8000}/snmpagent/
      - APP_SECRET=${API_SECRET:-mysecert123}
      - PORT=${API_PORT:-3333}

      - NODE_ENV=production

      - MAINDB_HOST=${DB_ADDR:-database}
      - MAINDB_PORT=${DB_PORT:-5432}
      - MAINDB_USER=${DB_USER:-postgres}
      - MAINDB_PASS=${DB_PASS:-somestrongpassword}
      - MAINDB_NAME=${DB_NAME:-friendly-system}
    ports:
      - ${API_PORT:-3333}:${API_PORT:-3333}
    networks:
      - fs_network
  
  app-snmpagent:
    build:
      context: ./snmpagent/
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PRODUCTION=True

      - SECRET_KEY=${API_SECRET:-mysecert123}

      - MAINDB_HOST=${DB_ADDR:-database}
      - MAINDB_PORT=${DB_PORT:-5432}
      - MAINDB_USER=${DB_USER:-postgres}
      - MAINDB_PASSWORD=${DB_PASS:-somestrongpassword}
      - MAINDB_NAME=${DB_NAME:-friendly-system}

      - ERPDB_ADDRESS=${ERPDB_ADDRESS:-127.0.0.1}
      - ERPDB_PORT=${ERPDB_PORT:-5432}
      - ERPDB_USER=${ERPDB_USER:-postgres}
      - ERPDB_PASSWORD=${ERPDB_PASSWORD:-somepassword}
      - ERPDB_DATABASE=${ERPDB_DATABASE:-database}
    networks:
      - fs_network

networks:
  fs_network:

volumes:
  fs_database:
  #fs_database-development: #attach development database
    #name: 98e19309c2840ebc09b508bd33de99bbb4a2a3973a4195dbdafce68710103cb6
    #external: true