

"""
Django settings for snmpagent project.
Generated by 'django-admin startproject' using Django 2.1.1.
For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import app
import configparser

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_DIR = pth = os.path.dirname(app.__file__)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
PRODUCTION  = os.environ.get("PRODUCTION", default=False)
DEBUG = not PRODUCTION

ALLOWED_HOSTS = ["0.0.0.0"]

print("Started in {} mode".format("PRODUCTION" if PRODUCTION else "DEVELOPMENT"))

# ENV FILE LOAD FOR DEVELOPMENT MODE
config_file_path = os.path.join(BASE_DIR, 'settings.ini')
config = configparser.RawConfigParser()

if config_file_path != None:
    print("Loading Enviroment Configuration File: " + config_file_path)
    config.read(config_file_path)
else:
    print("Enviroment Configuration File NOT FOUND, skipping")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "secret key") if PRODUCTION else config.get('system', 'SECRET_KEY')
ERPDB_ADDRESS = os.environ.get("ERPDB_ADDRESS", "127.0.0.1") if PRODUCTION else config.get('ERPDB', 'HOST')
ERPDB_PORT = os.environ.get("ERPDB_PORT", 5432) if PRODUCTION else config.get('ERPDB', 'PORT')
ERPDB_USER = os.environ.get("ERPDB_USER", "postgres") if PRODUCTION else config.get('ERPDB', 'USER')
ERPDB_PASSWORD = os.environ.get("ERPDB_PASSWORD", "password") if PRODUCTION else config.get('ERPDB', 'PASSWORD')
ERPDB_DATABASE = os.environ.get("ERPDB_DATABASE", "database") if PRODUCTION else config.get('ERPDB', 'NAME')

# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'app'
]

MIDDLEWARE = [
    #'django.middleware.security.SecurityMiddleware',
    #'django.contrib.sessions.middleware.SessionMiddleware',
    #'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    #'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'snmpagent.urls'

WSGI_APPLICATION = 'snmpagent.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': "django.db.backends.postgresql_psycopg2",
        'NAME': os.environ.get("MAINDB_NAME") if PRODUCTION else config.get('MAINDB', 'NAME'),
        'USER': os.environ.get("MAINDB_USER") if PRODUCTION else config.get('MAINDB', 'USER'),
        'PASSWORD': os.environ.get("MAINDB_PASSWORD") if PRODUCTION else config.get('MAINDB', 'PASSWORD'),
        'HOST': os.environ.get("MAINDB_HOST") if PRODUCTION else config.get('MAINDB', 'HOST'),
        'PORT': os.environ.get("MAINDB_PORT") if PRODUCTION else config.get('MAINDB', 'PORT'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get("TIME_ZONE", "America/Sao_Paulo") if PRODUCTION else config.get('system', 'TIME_ZONE')

USE_I18N = True

USE_L10N = True

USE_TZ = True
