'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.sequelize.query(
      `
        CREATE TABLE ap
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            erp_id integer NOT NULL,
            description character varying(100),
            oid_identification character varying(60),
            oid_identification_reduced character varying(60),
            address character varying(50),
            voice_vlan character varying(4),
            data_vlan character varying(4),
            snmp_port integer,
            snmp_community character varying(20),
            enabled boolean NOT NULL,
            CONSTRAINT ap_pkey PRIMARY KEY (id)
        );

        CREATE TABLE ap_available_oid
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            description character varying(100),
            oid character varying(60),
            oid_reduced character varying(60),
            ap_id integer,
            CONSTRAINT ap_available_oid_pkey PRIMARY KEY (id),
            CONSTRAINT ap_available_oid_ap_id_e488c789_fk_ap_id FOREIGN KEY (ap_id)
                REFERENCES ap (id) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE NO ACTION
                DEFERRABLE INITIALLY DEFERRED
        );

        CREATE TABLE cpe
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            erp_cpe_id integer NOT NULL,
            erp_ap_id integer NOT NULL,
            erp_contract_id integer,
            name character varying(100),
            username character varying(50),
            device_password character varying(50),
            mac_address character varying(50),
            onu_serial character varying(50),
            nap character varying(50),
            nap_port integer NOT NULL,
            technology character varying(1),
            cadastrado character varying(10),
            integration_updated boolean NOT NULL,
            observation character varying(1000),
            address_list character varying(50),
            last_snmp_index character varying(50),
            last_pon_index character varying(20),
            last_software_version character varying(30),
            last_hardware_version character varying(30),
            last_firmware_version character varying(30),
            last_onu_type integer NOT NULL,
            last_onu_serial character varying(20),
            last_rx double precision,
            last_tx double precision,
            online boolean NOT NULL,
            last_online timestamp with time zone,
            olt_matched boolean NOT NULL,
            CONSTRAINT cpe_pkey PRIMARY KEY (id)
        );

        CREATE TABLE cpe_record
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            erp_cpe_id integer NOT NULL,
            erp_ap_id integer NOT NULL,
            online boolean NOT NULL,
            snmp_index character varying(50),
            pon_index character varying(20),
            software_version character varying(30),
            hardware_version character varying(30),
            firmware_version character varying(30),
            onu_type integer NOT NULL,
            onu_serial character varying(20),
            rx double precision,
            tx double precision,
            wan_config boolean NOT NULL,
            onu_pon_type integer,
            onu_pon_enable_status integer,
            onu_pon_speed integer,
            onu_pon_optical_vltage integer,
            onu_pon_optical_current integer,
            onu_pon_optical_temperature integer,
            onu_pon_is_optical_power_valid integer,
            onu_pon_upstream_speed integer,
            onu_status integer,
            auth_onu_cpu_usage integer,
            auth_onu_memory_usage integer,
            auth_onu_mac_number_limit integer,
            auth_onu_mac_number_limit_apply integer,
            auth_onu_last_up character varying(100),
            auth_onu_last_down character varying(100),
            auth_onu_list_onu_type_description character varying(100),
            port_speed character varying(200),
            port_name character varying(200),
            port_mode character varying(200),
            port_vlan character varying(200),
            port_mac character varying(1000),
            pots_enable boolean NOT NULL,
            tel_num character varying(100),
            binding_signal_name character varying(100),
            signal_vlan character varying(200),
            protocol_port integer,
            username_sip_tel_num character varying(100),
            sip_username character varying(100),
            wan_index character varying(200),
            wan_conn_type character varying(200),
            wan_vlan_id character varying(200),
            wan_nat_enable character varying(200),
            wan_dsp character varying(200),
            wan_pppoe_username character varying(200),
            wan_pppoe_password character varying(200),
            wan_vlan_mode character varying(200),
            datetime timestamp with time zone NOT NULL,
            gpon_integration_id integer NOT NULL,
            CONSTRAINT cpe_record_pkey PRIMARY KEY (id)
        );

        CREATE TABLE cto_count
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            description character varying(100),
            online integer NOT NULL,
            offline integer NOT NULL,
            erp_ap_id integer NOT NULL,
            gpon_integration_id integer NOT NULL,
            CONSTRAINT cto_count_pkey PRIMARY KEY (id)
        );

        CREATE TABLE cto_rx_average
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            description character varying(100),
            value double precision NOT NULL,
            erp_ap_id integer NOT NULL,
            gpon_integration_id integer NOT NULL,
            CONSTRAINT cto_rx_average_pkey PRIMARY KEY (id)
        );

        CREATE TABLE cto_tx_average
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            description character varying(100),
            value double precision NOT NULL,
            erp_ap_id integer NOT NULL,
            gpon_integration_id integer NOT NULL,
            CONSTRAINT cto_tx_average_pkey PRIMARY KEY (id)
        );

        CREATE TABLE gpon_count
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            description character varying(100),
            online integer NOT NULL,
            offline integer NOT NULL,
            erp_ap_id integer NOT NULL,
            gpon_integration_id integer NOT NULL,
            CONSTRAINT gpon_count_pkey PRIMARY KEY (id)
        );

        CREATE TABLE gpon_integration
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            datetime timestamp with time zone NOT NULL,
            erp_ap_id integer NOT NULL,
            CONSTRAINT gpon_integration_pkey PRIMARY KEY (id)
        );

        CREATE TABLE gpon_rx_average
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            description character varying(100),
            value double precision NOT NULL,
            erp_ap_id integer NOT NULL,
            gpon_integration_id integer NOT NULL,
            CONSTRAINT gpon_rx_average_pkey PRIMARY KEY (id)
        );

        CREATE TABLE gpon_tx_average
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            description character varying(100),
            value double precision NOT NULL,
            erp_ap_id integer NOT NULL,
            gpon_integration_id integer NOT NULL,
            CONSTRAINT gpon_tx_average_pkey PRIMARY KEY (id)
        );

        CREATE TABLE gpon_unauthorized
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            description character varying(100),
            value double precision NOT NULL,
            datetime timestamp with time zone NOT NULL,
            erp_ap_id integer NOT NULL,
            CONSTRAINT gpon_unauthorized_pkey PRIMARY KEY (id)
        );

        CREATE TABLE onu_pon_info
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "onuPonIndex" character varying(20),
            onu_pon_type integer NOT NULL,
            onu_pon_name character varying(100),
            onu_pon_enable_status integer NOT NULL,
            onu_pon_speed integer NOT NULL,
            onu_pon_rx_optical_power integer NOT NULL,
            onu_pon_tx_optical_power integer NOT NULL,
            onu_pon_optical_vltage integer NOT NULL,
            onu_pon_optical_current integer NOT NULL,
            onu_pon_optical_temperature integer NOT NULL,
            onu_pon_is_optical_power_valid integer NOT NULL,
            onu_pon_upstream_speed integer NOT NULL,
            CONSTRAINT onu_pon_info_pkey PRIMARY KEY (id)
        );

        CREATE TABLE phone_prefix_city
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            prefix character varying(4),
            city character varying(50),
            CONSTRAINT phone_prefix_city_pkey PRIMARY KEY (id)
        );

        CREATE TABLE phone_subscriber
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            erp_contract_id integer,
            name character varying(100),
            phone_number character varying(50),
            plan_name character varying(150),
            product_name character varying(150),
            summit_license character varying(10),
            summit_category character varying(200),
            summit_partition character varying(200),
            city character varying(50),
            CONSTRAINT phone_subscriber_pkey PRIMARY KEY (id)
        );

        CREATE TABLE port_info_table
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "onuPonSubIndex" character varying(20),
            port_speed integer NOT NULL,
            port_name character varying(100),
            port_mode integer NOT NULL,
            port_vlan character varying(100),
            port_mac character varying(500),
            CONSTRAINT port_info_table_pkey PRIMARY KEY (id)
        );

        CREATE TABLE pots_user_cfg_list
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "onuPonIndex" character varying(20),
            pots_enable integer NOT NULL,
            tel_num character varying(100),
            binding_signal_name character varying(100),
            signal_vlan character varying(100),
            protocol_port integer NOT NULL,
            username_sip_tel_num character varying(100),
            sip_username character varying(100),
            CONSTRAINT pots_user_cfg_list_pkey PRIMARY KEY (id)
        );

        CREATE TABLE users
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            name character varying(50),
            email character varying(50),
            password_hash character varying(150),
            enabled boolean NOT NULL,
            created_at timestamp with time zone NOT NULL,
            updated_at timestamp with time zone NOT NULL,
            CONSTRAINT users_pkey PRIMARY KEY (id)
        );

        CREATE TABLE wan_service
        (
            id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            "onuPonIndex" character varying(20),
            wan_index integer NOT NULL,
            wan_conn_type integer NOT NULL,
            wan_vlan_id integer NOT NULL,
            wan_nat_enable integer NOT NULL,
            wan_dsp integer NOT NULL,
            wan_pppoe_username character varying(100),
            wan_pppoe_password character varying(100),
            wan_vlan_mode integer NOT NULL,
            CONSTRAINT wan_service_pkey PRIMARY KEY (id)
        );
      `
    );
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add reverting commands here.
     *
     * Example:
     * await queryInterface.dropTable('users');
     */
  }
};
