# Generated by Django 4.0.1 on 2022-01-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GponUnauthorized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('erp_ap_id', models.IntegerField()),
            ],
            options={
                'db_table': 'gpon_unauthorized',
            },
        ),
        migrations.AlterField(
            model_name='cperecord',
            name='port_mac',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
